
version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "8080:8080"
        expose:
            - "8080"
        image: kovacsmarcellsg/server:latest
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        image: kovacsmarcellsg/nginx:latest
    mysql:
        image: kovacsmarcellsg/db:latest
        build: ./mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
        
            
        ports:
            - "3306:3306"
            - "33060:33060"

        environment:
             MYSQL_ROOT_PASSWORD: Matyas53
             MYSQL_ROOT_HOST: "%"
             
        volumes:
            - mysql:/var/lib/mysql
    
    svelte:
        image: kovacsmarcellsg/svelte:latest
        restart: always
        build: ./svelte
        ports:
            - "3000:3000"
        expose:
            - "3000"
            
        command: ["yarn" ,"dev","--host","0.0.0.0"]
        
volumes:
    mysql: 