
version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "9000:9000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
    mysql:
        image: mysql:8
        build: ./mysql
        ports:
            - "3306:3306"
            - "33060:33060"
                
            
        