
version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "9000:9000"
        image: kovacsmarcellsg/bemutato:server
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        image: kovacsmarcellsg/bemutato:nginx
    mysql:
        image: kovacsmarcellsg/bemutato:db
        build: ./mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
        
            
        ports:
            - "3306:3306"
            - "33060:33060"

        environment:
             MYSQL_ROOT_PASSWORD: Matyas53
             MYSQL_ROOT_HOST: "%"
             
        volumes:
            - mysql:/var/lib/mysql
    
    svelte:
        image: kovacsmarcellsg/bemutato:svelte
        restart: always
        build: ./svelte
        ports:
            - "3000:3000"
            
        command: ["yarn" ,"dev","--host","0.0.0.0"]
        
            

    



volumes:
    mysql: 